// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Title","status":true,"description":"Adds Login, Logout, Register Options","parameters":{}},
{"name":"Login","status":true,"description":"Adds Login Functionality","parameters":{}},
{"name":"Register","status":true,"description":"Adds Register Functionality","parameters":{}}
];
